### ISSUE TITLE
LinkedIn login not working

### ISSUE THREAD

**Issue by simboonlong** [SaifurRahmanMohsin/Social-Plugin#5]
Hi Saifur,

I have manually deleted composer.lock and vendor folder before doing a force update.

When I attempt to sign in via Linkedin, this error appears:

"Cannot access protected property League\OAuth2\Client\Provider\LinkedIn::$state" on line 150 of <my_path_url>/social/components/LinkedIn.php"

Regards
Boon

**Comment by SaifurRahmanMohsin** [comment]
I have identified this error and pushed an update. Kindly verify if it is solved so that I can close this issue soon. Good day.

**Comment by simboonlong** [comment]
Yes it is fixed. Thank you for the swift response!

**Comment by SaifurRahmanMohsin** [comment]
Great. And thank you for the review.
